---

- name: install openssh-server package
  yum:
    name: openssh-server
  tags: openssh

- name: start and enable openssh-server
  service:
    name: sshd
    state: started
    enabled: yes
  tags: openssh

- name: copy configuration
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: restart openssh
  tags: openssh
